package client.gui.screens;

import client.Client;
import client.gui.ClientFrame;
import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author uross
 */
public class SignInScreen extends javax.swing.JPanel {

    /**
     * Creates new form LogIn
     *
     * @param _clientFrame
     * @param _client
     */
    public SignInScreen(ClientFrame _clientFrame, Client _client) {
        initComponents();

        clientFrame = _clientFrame;
        client = _client;

        signinButton.setContentAreaFilled(false);
        signinButton.setOpaque(true);
        signinButton.setBorder(new LineBorder(new Color(153, 153, 153)));

        requiredUsernameLabel.setForeground(Color.white);
        requiredPasswordLabel.setForeground(Color.white);
        errorLabel.setForeground(Color.white);

        CustomTextField username = (CustomTextField) usernameField;
        username.addDesignatedLabel(requiredUsernameLabel);
        username.addDesignatedLabel(errorLabel);

        CustomPasswordField password = (CustomPasswordField) passwordField;
        password.addDesignatedLabel(requiredPasswordLabel);
        password.addDesignatedLabel(errorLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        usernameField = new CustomTextField("Username");
        signinButton = new javax.swing.JButton();
        signupLabel = new javax.swing.JLabel();
        passwordField = new CustomPasswordField("Password");
        requiredUsernameLabel = new javax.swing.JLabel();
        requiredPasswordLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        logoLabel1 = new javax.swing.JLabel();

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/gui/res/logo.png"))); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 550));

        usernameField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        usernameField.setForeground(new java.awt.Color(153, 153, 153));
        usernameField.setText("Username");
        usernameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameField.setMargin(new java.awt.Insets(2, 15, 2, 2));

        signinButton.setBackground(new java.awt.Color(34, 156, 243));
        signinButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        signinButton.setForeground(new java.awt.Color(255, 255, 255));
        signinButton.setText("Sign In");
        signinButton.setFocusPainted(false);
        signinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signinButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signinButtonMouseExited(evt);
            }
        });
        signinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinButtonActionPerformed(evt);
            }
        });

        signupLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        signupLabel.setForeground(new java.awt.Color(34, 156, 243));
        signupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupLabel.setText("Don't have an account? Sign Up");
        signupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupLabelMouseExited(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        passwordField.setForeground(new java.awt.Color(153, 153, 153));
        passwordField.setText("Password");
        passwordField.setEchoChar('\u0000');
        passwordField.setMargin(new java.awt.Insets(2, 15, 2, 2));

        requiredUsernameLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        requiredUsernameLabel.setForeground(new java.awt.Color(255, 0, 0));
        requiredUsernameLabel.setText("Required");

        requiredPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        requiredPasswordLabel.setForeground(new java.awt.Color(255, 0, 0));
        requiredPasswordLabel.setText("Required");

        errorLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("Username or password is incorrect.");
        errorLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        errorLabel.setPreferredSize(new java.awt.Dimension(155, 18));

        logoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/gui/res/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordField)
                    .addComponent(requiredPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(requiredUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(signupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoLabel1)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(logoLabel1)
                .addGap(12, 12, 12)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(requiredUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requiredPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signupLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelMouseEntered
        signupLabel.setForeground(new Color(34, 115, 242));
    }//GEN-LAST:event_signupLabelMouseEntered

    private void signupLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelMouseExited
        signupLabel.setForeground(new Color(34, 156, 243));
    }//GEN-LAST:event_signupLabelMouseExited

    private void signupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelMouseClicked
        clientFrame.setActiveScreen(ScreenType.SIGNUP);
    }//GEN-LAST:event_signupLabelMouseClicked

    private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
        boolean inputValid = true;
        CustomTextField customUsernameField = (CustomTextField) usernameField;
        if (!customUsernameField.isInputValid()) {
            requiredUsernameLabel.setForeground(Color.red);
            inputValid = false;
        }

        CustomPasswordField customPasswordField = (CustomPasswordField) passwordField;
        if (!customPasswordField.isInputValid()) {
            requiredPasswordLabel.setForeground(Color.red);
            inputValid = false;
        }

        if (inputValid) {
            String response = client.signIn(usernameField.getText(), String.valueOf(passwordField.getPassword()));
            if (response.equals("OK")) {
                clientFrame.setActiveScreen(ScreenType.HOME);
                errorLabel.setForeground(Color.white);
            } else {
                errorLabel.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_signinButtonActionPerformed

    private void signinButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinButtonMouseEntered
        signinButton.setBackground(new Color(104, 185, 243));
    }//GEN-LAST:event_signinButtonMouseEntered

    private void signinButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinButtonMouseExited
        signinButton.setBackground(new Color(34, 156, 243));
    }//GEN-LAST:event_signinButtonMouseExited

    private ClientFrame clientFrame;
    private Client client;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel logoLabel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel requiredPasswordLabel;
    private javax.swing.JLabel requiredUsernameLabel;
    private javax.swing.JButton signinButton;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
